/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jon Mikel Merino
 */
public class InterfazCalculadora extends javax.swing.JFrame {
    
    private float operando;
    private String operador;
    
    /**
     * Creates new form NewJFrame
     */
    public InterfazCalculadora() {
        operando = 0;
        operador = "sin operacion";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        producto = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        division = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        uno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(230, 300));
        setSize(new java.awt.Dimension(230, 300));

        dos.setText("2");
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dosMouseClicked(evt);
            }
        });

        tres.setText("3");
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tresMouseClicked(evt);
            }
        });

        producto.setText("*");
        producto.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productoMouseClicked(evt);
            }
        });

        cero.setText("0");
        cero.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ceroMouseClicked(evt);
            }
        });

        punto.setText(".");
        punto.setActionCommand(".");
        punto.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                puntoMouseCliked(evt);
            }
        });

        igual.setText("=");
        igual.setAlignmentY(0.0F);
        igual.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                igualMouseClicked(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.setName(""); // NOI18N
        borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarMouseClicked(evt);
            }
        });

        division.setText("/");
        division.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisionMouseClicked(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarMouseClicked(evt);
            }
        });

        ocho.setText("8");
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ochoMouseClicked(evt);
            }
        });

        nueve.setText("9");
        nueve.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nueveMouseClicked(evt);
            }
        });

        siete.setText("7");
        siete.setToolTipText("");
        siete.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sieteMouseClicked(evt);
            }
        });

        suma.setText("+");
        suma.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumaMouseClicked(evt);
            }
        });

        cuatro.setText("4");
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuatroMouseClicked(evt);
            }
        });

        cinco.setText("5");
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincoMouseClicked(evt);
            }
        });

        seis.setText("6");
        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seisMouseClicked(evt);
            }
        });

        resta.setText("-");
        resta.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaMouseClicked(evt);
            }
        });

        uno.setText("1");
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(producto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(resultado))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(producto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void dosMouseClicked(java.awt.event.MouseEvent evt) {                                 
        resultado.setText(resultado.getText() + "2");
    }                                

    private void tresMouseClicked(java.awt.event.MouseEvent evt) {                                  
        resultado.setText(resultado.getText() + "3");
    }                                 

    private void productoMouseClicked(java.awt.event.MouseEvent evt) {                                      
        try{ 
            if (!resultado.getText().equals(""))
                operando = Float.parseFloat(resultado.getText());
            else 
                JOptionPane.showMessageDialog(null, "Formato de operación no válido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Formato de operador no válido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        operador = "producto";
        resultado.setText("");
    }                                     
    
    private void calcular() {
        
        LogicaCalculadora lc = new LogicaCalculadora();
        float resul = 0;
        float op1 = operando;
        float op2 = 0;
        try{ 
           if (!resultado.getText().equals(""))
               op2 = Float.parseFloat(resultado.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Formato de operador no válido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        try{
            switch(operador){
                case "suma":
                    resul = lc.suma(op1,op2);
                    break;
                case "resta":
                    resul = lc.resta(op1,op2);
                    break;
                case "producto":
                    resul = lc.producto(op1,op2);
                    break;
                case "division":
                        resul = lc.division(op1,op2);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "No exite operador", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }catch(ArithmeticException e){
            JOptionPane.showMessageDialog(null, "Error aritmético: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        resultado.setText("" + resul);
        
        
        try (PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(new File("historial.txt"),true)))) {
            String line = Global.user+" "+resul;
            out.println(line);
        } catch (IOException ex) {
            Logger.getLogger(InterfazCalculadora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void igualMouseClicked(java.awt.event.MouseEvent evt) {                                   
        calcular();
    }                                  

    private void divisionMouseClicked(java.awt.event.MouseEvent evt) {                                      
        try{ 
            if (!resultado.getText().equals(""))
                operando = Float.parseFloat(resultado.getText());
            else 
                JOptionPane.showMessageDialog(null, "Formato de operación no válido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Formato de operador no válido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        operador = "division";
        resultado.setText("");
    }                                     

    private void limpiarMouseClicked(java.awt.event.MouseEvent evt) {                                     
        resultado.setText("");
    }                                    

    private void ochoMouseClicked(java.awt.event.MouseEvent evt) {                                  
        resultado.setText(resultado.getText() + "8");
    }                                 

    private void nueveMouseClicked(java.awt.event.MouseEvent evt) {                                   
        resultado.setText(resultado.getText() + "9");
    }                                  

    private void sieteMouseClicked(java.awt.event.MouseEvent evt) {                                   
        resultado.setText(resultado.getText() + "7");
    }                                  

    private void sumaMouseClicked(java.awt.event.MouseEvent evt) {                                  
        try{ 
            if (!resultado.getText().equals(""))
                operando = Float.parseFloat(resultado.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Formato de operador no válido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        operador = "suma";
        resultado.setText("");

    }                                 

    private void cuatroMouseClicked(java.awt.event.MouseEvent evt) {                                    
        resultado.setText(resultado.getText() + "4");
    }                                   

    private void cincoMouseClicked(java.awt.event.MouseEvent evt) {                                   
        resultado.setText(resultado.getText() + "5");
    }                                  

    private void seisMouseClicked(java.awt.event.MouseEvent evt) {                                  
        resultado.setText(resultado.getText() + "6");
    }                                 

    private void restaMouseClicked(java.awt.event.MouseEvent evt) {                                   
        try{ 
            if (!resultado.getText().equals(""))
                operando = Float.parseFloat(resultado.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Formato de operador no válido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }         
        operador = "resta";
        resultado.setText("");
    }                                  

    private void unoMouseClicked(java.awt.event.MouseEvent evt) {                                 
        resultado.setText(resultado.getText() + "1");
    }                                

    private void ceroMouseClicked(java.awt.event.MouseEvent evt) {                                  
        resultado.setText(resultado.getText() + "0");
    }                                 

    private void puntoMouseCliked(java.awt.event.MouseEvent evt) {                                  
        resultado.setText(resultado.getText() + ".");
    }                                 

    private void borrarMouseClicked(java.awt.event.MouseEvent evt) {                                    
        if (!resultado.getText().equals(""))
            resultado.setText(resultado.getText().substring(0, resultado.getText().length()-1));
    }                                   

    

    // Variables declaration - do not modify                     
    private javax.swing.JButton borrar;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton division;
    private javax.swing.JButton dos;
    private javax.swing.JButton igual;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton producto;
    private javax.swing.JButton punto;
    private javax.swing.JButton resta;
    private javax.swing.JTextField resultado;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton suma;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration                   
}
